In [2]:
import pandas as pd
from pycaret.datasets import get_data
from pycaret.classification import *

data = pd.read_csv('C:/Users/ekyfe/Documents/college/Semester 4/MLOps/praktikum/stroke/healthcare-dataset-stroke-data.csv')

# Drop the 'id' column
data.drop(columns=['id'], inplace=True)

# Fill missing values with mean
data.fillna(data.mean(), inplace=True)

# Setup PyCaret
s = setup(data, target='stroke', session_id=123)

# Compare models
best = compare_models()

# Tune best model
model = tune_model(best)

# Evaluate model
evaluate_model(model)

# Finalize model
finalize_model(model)

# Save model
save_model(model, 'stroke_pipeline')

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['age', 'hypertension',
                                              'heart_disease',
                                              'avg_glucose_level', 'bmi'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  TransformerWrapper(e...
                                     transformer=OneHotEncoder(cols=['gender',
                                                                     'work_type',
                                                                     'smoking_status'],
                                                               drop_invariant=False,
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               return_df=True,
                                                               use_cat_names=True,
                                                               verbose=0))),
                 ('trained_model',
                  RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                  fit_intercept=True, max_iter=None,
                                  positive=False, random_state=123,
                                  solver='auto', tol=0.0001))],
          verbose=False),
 'stroke_pipeline.pkl')

In [3]:
import pandas as pd
data = pd.read_csv('C:/Users/ekyfe/Documents/college/Semester 4/MLOps/praktikum/stroke/healthcare-dataset-stroke-data.csv')
data.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000